### ISSUE TITLE
Reportportal extension selenium isn't sending data to reportportal service

### ISSUE THREAD

**Issue by testingplusme** [nvborisenko/reportportal-extensions-selenium#1]
Hey Nikolay,
First of all, I need to appreciate what did you do :) It's awesome that you do this type of extension. I wanted to develop by myself but I see that you did it 👍 
I have a problem with the extension I added to my code your extension method but when I ran tests from NUnit Console Runner and it doesn't work. I have a connection with my reportportal because I can see that tests were running but without logs from the tests? Can you help me?

Best Regards,
Michal

**Comment by nvborisenko** [comment]
Good to hear you are interesting it. Is it possible to create a very small test project to reproduce the issue?

**Comment by testingplusme** [comment]
Ofc, I put my solution there -> It's working test reportportal service in my config so please test with it
https://github.com/testingplusme/ReportPortalExampleNet project SeleniumExampleTests

**Comment by nvborisenko** [comment]
I reproduced it, and this is bug. As a workaround please install `NUnit3TestAdapter` nuget package and it will work.

**Comment by testingplusme** [comment]
Thanks, it's working now :)

**Comment by nvborisenko** [comment]
The issue is resolved in ReportPortal.NUnit v3.7.11. You are not required to apply workaround.

Thanks for the issue. I'm closing it.
