### ISSUE TITLE
remove markdown prefix when reporting to v5 reportportal

### ISSUE THREAD

**Issue by tuscias** [nvborisenko/reportportal-extensions-selenium#2]
ReportPortal v5 has an UI button to switch from ordinary log messages to markdown so 
!!!MARKDOWN_MODE!!! prefix is not needed anymore.

**Comment by nvborisenko** [comment]
I see 2 options:
- make it configurable on here (on/off)
- this is bug of RP, v5 is not fully compatible with old clients

**Comment by tuscias** [comment]
It would be great if it were configurable, because rp v5 changed how it handles markdown.
You can try it on v5 deployment https://beta.demo.reportportal.io/ui/

**Comment by nvborisenko** [comment]
Submitted a bug for backend: https://github.com/reportportal/reportportal/issues/746

**Comment by tuscias** [comment]
> Submitted a bug for backend: [reportportal/reportportal#746](https://github.com/reportportal/reportportal/issues/746)

backend closed that bug

**Comment by nvborisenko** [comment]
New version of the package doesn't send prefix by default.
